
#datasource postgresql
spring.application.name=batch
spring.datasource.url=jdbc:postgresql://localhost:5432/batch_db
spring.datasource.username=postgres
spring.datasource.password=1
spring.datasource.driver-class-name=org.postgresql.Driver

#auto create metadata
spring.batch.jdbc.initialize-schema=always

#nonaktifkan auto-run job saat startup(recomended)
spring.batch.job.enabled=false